name: AI Code-Review
author: SAK74
description: Conduct code-review & PR description by AI based on git diff
inputs:
  OPENAI_API_KEY:
    required: true
    description: OPENAI_API_KEY

  with-comment:
    required: false
    description: should be PR commented
    default: "false"

runs:
  using: node20
  main: dist/index.js
