name: AI Code-Review
author: SAK74
description: Conduct code-review by AI based on git diff
inputs:
  GITHUB_TOKEN:
    required: true
    description: GITHUB_TOKEN

runs:
  using: node20
  main: dist/index.js
