name: Test workflow
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test-job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 #required to git history access
        name: Checkout repository

      - uses: "./"
        name: Call action
        with:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          with-comment: true # optional to make comment (default false)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # reqired
