name: Test workflow
on:
  pull_request:
    types: [opened, edited]
  # push:
  #   branches: [master]
  # workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "PR:" ${{github.event.pull_request.number}}
      - run: echo "PR:" ${{github.event.repository}}
      # - run: echo ${{job.status}}

      # - run: ${{github.event}}

      # - name: Node setup
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.x

      - uses: "./"
