name: Test workflow
on:
  pull_request:
    types: [opened, edited, reopened]
  # push:
  #   branches: [master]
  # workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      repository-projects: write
    steps:
      - uses: actions/checkout@v4

      # - run: echo "PR:" ${{github.event.pull_request.diff_url}}
      # - run: echo "PR:" ${{github.event.pull_request.body}}
      # - run: echo ${{job.status}}

      # - run: ${{github.event}}

      # - name: Node setup
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.x

      - uses: "./"
        with:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
