name: Test workflow
# on: workflow_dispatch
on: pull_request
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo ${{github.event.pull_request}}
      # - run: echo ${{job.status}}

      # - run: ${{github.event}}

      - uses: "./"

      # any changes
